// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9FJYi6WAS0PSwFxBBlMhzuCo7A9XPnfY',
    appId: '1:242655922984:web:bfbd79271d076de9221e1d',
    messagingSenderId: '242655922984',
    projectId: 'muhammad-rashid-a782a',
    authDomain: 'muhammad-rashid-a782a.firebaseapp.com',
    storageBucket: 'muhammad-rashid-a782a.firebasestorage.app',
    measurementId: 'G-V1GQPQSVXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnQbdPVwxphZZusr_LGmESyY3KPhP9l3g',
    appId: '1:242655922984:android:afc08148490f9bbc221e1d',
    messagingSenderId: '242655922984',
    projectId: 'muhammad-rashid-a782a',
    storageBucket: 'muhammad-rashid-a782a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWSiCOlDxD7BmkXR-5mz3wHR3Wgswj3-E',
    appId: '1:242655922984:ios:86517f83d84a4424221e1d',
    messagingSenderId: '242655922984',
    projectId: 'muhammad-rashid-a782a',
    storageBucket: 'muhammad-rashid-a782a.firebasestorage.app',
    iosBundleId: 'com.example.rashidCodes',
  );
}
